### PR TITLE
Convert the project to maven... again

### PR DESCRIPTION
**Pull request by Azzurite**
Actually, it didn't take long at all.

See https://github.com/JEFF-Media-GbR/Spigot-ChestSort/pull/7

### CODE REVIEW

**Comment by mfnalex** [comment]
Thanks for your patience with me lol

**Comment by mfnalex** [comment]
Just out of curiosity: what IDE do you use?

**Comment by Azzurite** [comment]
I use IntelliJ. I also used Eclipse when I started out, but after I gave IntelliJ a serious try, it's impossible for me to go back again.

**Comment by mfnalex** [comment]
I will have a look, thanks. By the way, I was bored and found the open source application Gource. I made a quick video of ChestSort's git repo :) https://www.youtube.com/watch?v=XnqY5FX6FX0

**Pull request merged**
