### PR TITLE
Fixed a bug

### PR DESCRIPTION
**Pull request by Margele**
It will cause the item to disappear in the plugin GUI, I fixed it

### CODE REVIEW

**Comment by mfnalex** [comment]
Thanks. Before testing and merging: can you please explain in what circumstances the items disappear?

**Comment by Margele** [comment]
> 谢谢。在测试和合并之前：您能否解释一下这些项目在什么情况下消失？
Use /chestsort hotkey to call GUI, put something in the gui, then items can not be moved.

**Comment by Margele** [comment]
> Thanks. Before testing and merging: can you please explain in what circumstances the items disappear?

Use /chestsort hotkey to call GUI, put something in the gui, then items can not be moved.

**Comment by mfnalex** [comment]
Oh, I didn't know it was possible to put items into the GUI. Thanks - update will be released soon.

**Comment by mfnalex** [comment]
Thank you, has been fixed inside the existing onInventoryClickEvent method. Will be released in 7.3.1 or 7.4

**Pull request closed without merging**
