### PR TITLE
Compatiblity with GoldenCrates plugin

### PR DESCRIPTION
**Pull request by xmssss**
https://www.spigotmc.org/resources/goldencrates-•-advanced-custom-crates-1-14-1-16.48732/

### CODE REVIEW

**Comment by mfnalex** [comment]
Thank you! I believe you tested this, right? If so I trust you and will release it tomorrow^^

**Comment by xmssss** [comment]
Yes, tested

**Comment by xmssss** [comment]
If some broke, i tell you first. But nothing could break. Thx)

**Comment by mfnalex** [comment]
Update is released (9.1.0 on SpigotMC) :)

**Pull request merged**
